/**
 * Curated coin-name → Binance base asset aliases for headline matching.
 * Multi-word names must sort before their prefixes (longest-first matching
 * happens in detect.ts). Every hit is still validated against the live
 * exchange symbol list — a stale row here can never invent a symbol.
 */
export const COIN_NAME_ALIASES: ReadonlyArray<readonly [string, string]> = [
  ["bitcoin cash", "BCH"],
  ["bitcoin sv", "BSV"],
  ["ethereum classic", "ETC"],
  ["shiba inu", "SHIB"],
  ["internet computer", "ICP"],
  ["the graph", "GRT"],
  ["the sandbox", "SAND"],
  ["lido dao", "LDO"],
  ["curve dao", "CRV"],
  ["pancakeswap", "CAKE"],
  ["bitcoin", "BTC"],
  ["ethereum", "ETH"],
  ["ether", "ETH"],
  ["solana", "SOL"],
  ["ripple", "XRP"],
  ["xrp", "XRP"],
  ["dogecoin", "DOGE"],
  ["doge", "DOGE"],
  ["cardano", "ADA"],
  ["avalanche", "AVAX"],
  ["chainlink", "LINK"],
  ["polkadot", "DOT"],
  ["polygon", "POL"],
  ["litecoin", "LTC"],
  ["tron", "TRX"],
  ["toncoin", "TON"],
  ["cosmos", "ATOM"],
  ["near protocol", "NEAR"],
  ["aptos", "APT"],
  ["arbitrum", "ARB"],
  ["optimism", "OP"],
  ["sui", "SUI"],
  ["sei", "SEI"],
  ["celestia", "TIA"],
  ["injective", "INJ"],
  ["render", "RENDER"],
  ["filecoin", "FIL"],
  ["hedera", "HBAR"],
  ["stellar", "XLM"],
  ["vechain", "VET"],
  ["algorand", "ALGO"],
  ["fantom", "FTM"],
  ["aave", "AAVE"],
  ["uniswap", "UNI"],
  ["maker", "MKR"],
  ["compound", "COMP"],
  ["synthetix", "SNX"],
  ["pepe", "PEPE"],
  ["bonk", "BONK"],
  ["floki", "FLOKI"],
  ["dogwifhat", "WIF"],
  ["jupiter", "JUP"],
  ["pyth network", "PYTH"],
  ["worldcoin", "WLD"],
  ["monero", "XMR"],
  ["zcash", "ZEC"],
  ["dash", "DASH"],
  ["eos", "EOS"],
  ["tezos", "XTZ"],
  ["theta", "THETA"],
  ["axie infinity", "AXS"],
  ["decentraland", "MANA"],
  ["gala", "GALA"],
  ["immutable", "IMX"],
  ["flow", "FLOW"],
  ["chiliz", "CHZ"],
  ["enjin", "ENJ"],
  ["mask network", "MASK"],
  ["ocean protocol", "OCEAN"],
  ["fetch.ai", "FET"],
  ["singularitynet", "AGIX"],
  ["binance coin", "BNB"],
  ["bnb", "BNB"],
  ["kaspa", "KAS"],
  ["mantle", "MNT"],
  ["starknet", "STRK"],
  ["zksync", "ZK"],
  ["ethena", "ENA"],
  ["ondo", "ONDO"],
  ["jito", "JTO"],
  ["raydium", "RAY"],
  ["hyperliquid", "HYPE"],
  ["stacks", "STX"],
  ["thorchain", "RUNE"],
  ["kava", "KAVA"],
  ["klaytn", "KLAY"],
  ["mina", "MINA"],
  ["neo", "NEO"],
  ["iota", "IOTA"],
  ["waves", "WAVES"],
  ["harmony", "ONE"],
  ["zilliqa", "ZIL"],
  ["basic attention token", "BAT"],
  ["yearn.finance", "YFI"],
  ["sushiswap", "SUSHI"],
  ["1inch", "1INCH"],
  ["dydx", "DYDX"],
  ["gmx", "GMX"],
  ["blur", "BLUR"],
  ["magic eden", "ME"],
  ["official trump", "TRUMP"],
  ["fartcoin", "FARTCOIN"],
];

/**
 * Base assets that collide with common English/headline words. A bare
 * symbol match on one of these only counts when the same base was also
 * found via cashtag or full-name match.
 */
export const AMBIGUOUS_BASES = new Set([
  "ONE",
  "GAS",
  "ACT",
  "WIN",
  "JST",
  "T",
  "OP",
  "FLOW",
  "DASH",
  "MASK",
  "HOT",
  "SUN",
  "COS",
  "ME",
  "NOW",
  "HIGH",
  "MOVE",
  "PORTAL",
  "PROM",
  "REI",
  "OM",
  "ARK",
  "AI",
  "TRUMP",
  "HYPE",
]);
